// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { DbVector2 } from "./db_vector_2_type";
// Mark import as potentially unused
declare type __keep_DbVector2 = DbVector2;


export type BattleUnit = {
  id: bigint,
  battleId: bigint,
  crewId: bigint,
  owner: __Identity,
  side: number,
  position: DbVector2,
  velocity: DbVector2,
  radius: number,
  maxHp: number,
  currentHp: number,
  attack: number,
  defense: number,
  abilityPower: number,
  magicResist: number,
  attackSpeed: number,
  critChance: number,
  critDamage: number,
  maxMana: number,
  currentMana: number,
  manaPerAttack: number,
  attackCooldown: number,
  targetUnitId: bigint | undefined,
  abilityReady: boolean,
  abilityCooldown: number,
  isStunned: boolean,
  stunDuration: number,
};
let _cached_BattleUnit_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const BattleUnit = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_BattleUnit_type_value) return _cached_BattleUnit_type_value;
    _cached_BattleUnit_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_BattleUnit_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "battleId", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "crewId", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "owner", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "side", algebraicType: __AlgebraicTypeValue.U8 },
      { name: "position", algebraicType: DbVector2.getTypeScriptAlgebraicType() },
      { name: "velocity", algebraicType: DbVector2.getTypeScriptAlgebraicType() },
      { name: "radius", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "maxHp", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "currentHp", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "attack", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "defense", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "abilityPower", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "magicResist", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "attackSpeed", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "critChance", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "critDamage", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "maxMana", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "currentMana", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "manaPerAttack", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "attackCooldown", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "targetUnitId", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.U64) },
      { name: "abilityReady", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "abilityCooldown", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "isStunned", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "stunDuration", algebraicType: __AlgebraicTypeValue.F32 },
    );
    return _cached_BattleUnit_type_value;
  },

  serialize(writer: __BinaryWriter, value: BattleUnit): void {
    __AlgebraicTypeValue.serializeValue(writer, BattleUnit.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): BattleUnit {
    return __AlgebraicTypeValue.deserializeValue(reader, BattleUnit.getTypeScriptAlgebraicType());
  },

}

export default BattleUnit;


