// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { BattleStatus } from "./battle_status_type";
// Mark import as potentially unused
declare type __keep_BattleStatus = BattleStatus;


export type Battle = {
  id: bigint,
  player1: __Identity,
  player2: __Identity | undefined,
  winner: __Identity | undefined,
  status: BattleStatus,
  turn: number,
  bountyReward: number,
  player1Bounty: number,
  player2Bounty: number,
};
let _cached_Battle_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Battle = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Battle_type_value) return _cached_Battle_type_value;
    _cached_Battle_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Battle_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "player1", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "player2", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createIdentityType()) },
      { name: "winner", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createIdentityType()) },
      { name: "status", algebraicType: BattleStatus.getTypeScriptAlgebraicType() },
      { name: "turn", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "bountyReward", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "player1Bounty", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "player2Bounty", algebraicType: __AlgebraicTypeValue.U32 },
    );
    return _cached_Battle_type_value;
  },

  serialize(writer: __BinaryWriter, value: Battle): void {
    __AlgebraicTypeValue.serializeValue(writer, Battle.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Battle {
    return __AlgebraicTypeValue.deserializeValue(reader, Battle.getTypeScriptAlgebraicType());
  },

}

export default Battle;


