// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { CompletedItem } from "./completed_item_type";
// Mark import as potentially unused
declare type __keep_CompletedItem = CompletedItem;


export type CompletedItemStats = {
  item: CompletedItem,
  name: string,
  description: string,
  bonusAd: number,
  bonusCritChance: number,
  bonusCritDamage: number,
  bonusAttackSpeed: number,
  bonusAp: number,
  bonusArmor: number,
  bonusMr: number,
  bonusMana: number,
  bonusHp: number,
  bonusHpRegen: number,
  hasSplash: boolean,
  armorShred: number,
};
let _cached_CompletedItemStats_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const CompletedItemStats = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_CompletedItemStats_type_value) return _cached_CompletedItemStats_type_value;
    _cached_CompletedItemStats_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_CompletedItemStats_type_value.value.elements.push(
      { name: "item", algebraicType: CompletedItem.getTypeScriptAlgebraicType() },
      { name: "name", algebraicType: __AlgebraicTypeValue.String },
      { name: "description", algebraicType: __AlgebraicTypeValue.String },
      { name: "bonusAd", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "bonusCritChance", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "bonusCritDamage", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "bonusAttackSpeed", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "bonusAp", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "bonusArmor", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "bonusMr", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "bonusMana", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "bonusHp", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "bonusHpRegen", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "hasSplash", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "armorShred", algebraicType: __AlgebraicTypeValue.I32 },
    );
    return _cached_CompletedItemStats_type_value;
  },

  serialize(writer: __BinaryWriter, value: CompletedItemStats): void {
    __AlgebraicTypeValue.serializeValue(writer, CompletedItemStats.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): CompletedItemStats {
    return __AlgebraicTypeValue.deserializeValue(reader, CompletedItemStats.getTypeScriptAlgebraicType());
  },

}

export default CompletedItemStats;


