// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as CompletedItemVariants from './completed_item_variants'

// The tagged union or sum type for the algebraic type `CompletedItem`.
export type CompletedItem = CompletedItemVariants.Yoru |
  CompletedItemVariants.Kabuto |
  CompletedItemVariants.Shusui |
  CompletedItemVariants.ClimaTact |
  CompletedItemVariants.ThunderTempo |
  CompletedItemVariants.MirageFlower |
  CompletedItemVariants.AdamWood |
  CompletedItemVariants.SeaKingScale |
  CompletedItemVariants.ThousandSunnyHull |
  CompletedItemVariants.VivrCard |
  CompletedItemVariants.LogPose |
  CompletedItemVariants.Poneglyph |
  CompletedItemVariants.GumGumFruit |
  CompletedItemVariants.GomuGomuNoMi |
  CompletedItemVariants.HakiMastery;

let _cached_CompletedItem_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const CompletedItem = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Yoru: { tag: "Yoru" } as const,
  Kabuto: { tag: "Kabuto" } as const,
  Shusui: { tag: "Shusui" } as const,
  ClimaTact: { tag: "ClimaTact" } as const,
  ThunderTempo: { tag: "ThunderTempo" } as const,
  MirageFlower: { tag: "MirageFlower" } as const,
  AdamWood: { tag: "AdamWood" } as const,
  SeaKingScale: { tag: "SeaKingScale" } as const,
  ThousandSunnyHull: { tag: "ThousandSunnyHull" } as const,
  VivrCard: { tag: "VivrCard" } as const,
  LogPose: { tag: "LogPose" } as const,
  Poneglyph: { tag: "Poneglyph" } as const,
  GumGumFruit: { tag: "GumGumFruit" } as const,
  GomuGomuNoMi: { tag: "GomuGomuNoMi" } as const,
  HakiMastery: { tag: "HakiMastery" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_CompletedItem_type_value) return _cached_CompletedItem_type_value;
    _cached_CompletedItem_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_CompletedItem_type_value.value.variants.push(
      { name: "Yoru", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Kabuto", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Shusui", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "ClimaTact", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "ThunderTempo", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "MirageFlower", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "AdamWood", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "SeaKingScale", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "ThousandSunnyHull", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "VivrCard", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "LogPose", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Poneglyph", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "GumGumFruit", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "GomuGomuNoMi", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "HakiMastery", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_CompletedItem_type_value;
  },

  serialize(writer: __BinaryWriter, value: CompletedItem): void {
      __AlgebraicTypeValue.serializeValue(writer, CompletedItem.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): CompletedItem {
      return __AlgebraicTypeValue.deserializeValue(reader, CompletedItem.getTypeScriptAlgebraicType());
  },

}

export default CompletedItem;


