// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as CrewTraitVariants from './crew_trait_variants'

// The tagged union or sum type for the algebraic type `CrewTrait`.
export type CrewTrait = CrewTraitVariants.StrawHat |
  CrewTraitVariants.Marine |
  CrewTraitVariants.Revolutionary |
  CrewTraitVariants.Warlord |
  CrewTraitVariants.Emperor |
  CrewTraitVariants.Supernova |
  CrewTraitVariants.DfUser;

// A value with helper functions to construct the type.
export const CrewTrait = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  StrawHat: { tag: "StrawHat" } as const,
  Marine: { tag: "Marine" } as const,
  Revolutionary: { tag: "Revolutionary" } as const,
  Warlord: { tag: "Warlord" } as const,
  Emperor: { tag: "Emperor" } as const,
  Supernova: { tag: "Supernova" } as const,
  DFUser: { tag: "DFUser" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "StrawHat", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Marine", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Revolutionary", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Warlord", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Emperor", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Supernova", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "DFUser", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: CrewTrait): void {
      __AlgebraicTypeValue.serializeValue(writer, CrewTrait.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): CrewTrait {
      return __AlgebraicTypeValue.deserializeValue(reader, CrewTrait.getTypeScriptAlgebraicType());
  },

}

export default CrewTrait;


