// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type DbVector2 = {
  x: number,
  y: number,
};
let _cached_DbVector2_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const DbVector2 = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_DbVector2_type_value) return _cached_DbVector2_type_value;
    _cached_DbVector2_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_DbVector2_type_value.value.elements.push(
      { name: "x", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "y", algebraicType: __AlgebraicTypeValue.F32 },
    );
    return _cached_DbVector2_type_value;
  },

  serialize(writer: __BinaryWriter, value: DbVector2): void {
    __AlgebraicTypeValue.serializeValue(writer, DbVector2.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): DbVector2 {
    return __AlgebraicTypeValue.deserializeValue(reader, DbVector2.getTypeScriptAlgebraicType());
  },

}

export default DbVector2;


