// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { ShipUpgradeType } from "./ship_upgrade_type_type";
// Mark import as potentially unused
declare type __keep_ShipUpgradeType = ShipUpgradeType;


export type PlayerShipUpgrade = {
  id: bigint,
  owner: __Identity,
  upgradeType: ShipUpgradeType,
  acquiredAtFight: number,
};
let _cached_PlayerShipUpgrade_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const PlayerShipUpgrade = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_PlayerShipUpgrade_type_value) return _cached_PlayerShipUpgrade_type_value;
    _cached_PlayerShipUpgrade_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_PlayerShipUpgrade_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "owner", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "upgradeType", algebraicType: ShipUpgradeType.getTypeScriptAlgebraicType() },
      { name: "acquiredAtFight", algebraicType: __AlgebraicTypeValue.U32 },
    );
    return _cached_PlayerShipUpgrade_type_value;
  },

  serialize(writer: __BinaryWriter, value: PlayerShipUpgrade): void {
    __AlgebraicTypeValue.serializeValue(writer, PlayerShipUpgrade.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PlayerShipUpgrade {
    return __AlgebraicTypeValue.deserializeValue(reader, PlayerShipUpgrade.getTypeScriptAlgebraicType());
  },

}

export default PlayerShipUpgrade;


