// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { CrewTrait } from "./crew_trait_type";
// Mark import as potentially unused
declare type __keep_CrewTrait = CrewTrait;
import { ShipType } from "./ship_type_type";
// Mark import as potentially unused
declare type __keep_ShipType = ShipType;


export type Player = {
  identity: __Identity,
  name: string,
  berries: number,
  bounty: number,
  wins: number,
  losses: number,
  shipType: ShipType,
  online: boolean,
  fightsCompleted: number,
  activeTrait: CrewTrait | undefined,
  traitLevel: number,
};
let _cached_Player_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Player = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Player_type_value) return _cached_Player_type_value;
    _cached_Player_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Player_type_value.value.elements.push(
      { name: "identity", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "name", algebraicType: __AlgebraicTypeValue.String },
      { name: "berries", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "bounty", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "wins", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "losses", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "shipType", algebraicType: ShipType.getTypeScriptAlgebraicType() },
      { name: "online", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "fightsCompleted", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "activeTrait", algebraicType: __AlgebraicTypeValue.createOptionType(CrewTrait.getTypeScriptAlgebraicType()) },
      { name: "traitLevel", algebraicType: __AlgebraicTypeValue.U32 },
    );
    return _cached_Player_type_value;
  },

  serialize(writer: __BinaryWriter, value: Player): void {
    __AlgebraicTypeValue.serializeValue(writer, Player.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Player {
    return __AlgebraicTypeValue.deserializeValue(reader, Player.getTypeScriptAlgebraicType());
  },

}

export default Player;


