// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type BonusGold = { tag: "BonusGold" };
export type BonusHealth = { tag: "BonusHealth" };
export type BonusAttack = { tag: "BonusAttack" };
export type BonusDefense = { tag: "BonusDefense" };
export type BonusSpeed = { tag: "BonusSpeed" };
export type StrawHatBuff = { tag: "StrawHatBuff" };
export type MarineBuff = { tag: "MarineBuff" };
export type RevolutionaryBuff = { tag: "RevolutionaryBuff" };
export type LogiaBuff = { tag: "LogiaBuff" };
export type ParameciaBuff = { tag: "ParameciaBuff" };
export type ZoanBuff = { tag: "ZoanBuff" };
export type GamblerLuck = { tag: "GamblerLuck" };
export type FastLearner = { tag: "FastLearner" };
export type Plunderer = { tag: "Plunderer" };
export type Medic = { tag: "Medic" };
export type Arsenal = { tag: "Arsenal" };

