// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { ShipUpgradeData } from "./ship_upgrade_data_type";
import { ShipUpgradeType } from "./ship_upgrade_type_type";
// Mark import as potentially unused
declare type __keep_ShipUpgradeType = ShipUpgradeType;

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `ship_upgrade_data`.
 *
 * Obtain a handle from the [`shipUpgradeData`] property on [`RemoteTables`],
 * like `ctx.db.shipUpgradeData`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.shipUpgradeData.on_insert(...)`.
 */
export class ShipUpgradeDataTableHandle<TableName extends string> implements __TableHandle<TableName> {
  // phantom type to track the table name
  readonly tableName!: TableName;
  tableCache: __TableCache<ShipUpgradeData>;

  constructor(tableCache: __TableCache<ShipUpgradeData>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ShipUpgradeData> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `ship_upgrade_data`,
   * which allows point queries on the field of the same name
   * via the [`ShipUpgradeDataIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.shipUpgradeData.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `ship_upgrade_data`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): ShipUpgradeData | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `upgradeType` unique index on the table `ship_upgrade_data`,
   * which allows point queries on the field of the same name
   * via the [`ShipUpgradeDataUpgradeTypeUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.shipUpgradeData.upgradeType().find(...)`.
   *
   * Get a handle on the `upgradeType` unique index on the table `ship_upgrade_data`.
   */
  upgradeType = {
    // Find the subscribed row whose `upgradeType` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: ShipUpgradeType): ShipUpgradeData | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.upgradeType, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ShipUpgradeData) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ShipUpgradeData) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ShipUpgradeData) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ShipUpgradeData) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ShipUpgradeData, newRow: ShipUpgradeData) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ShipUpgradeData, newRow: ShipUpgradeData) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
