// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as ShipUpgradeTypeVariants from './ship_upgrade_type_variants'

// The tagged union or sum type for the algebraic type `ShipUpgradeType`.
export type ShipUpgradeType = ShipUpgradeTypeVariants.BonusGold |
  ShipUpgradeTypeVariants.BonusHealth |
  ShipUpgradeTypeVariants.BonusAttack |
  ShipUpgradeTypeVariants.BonusDefense |
  ShipUpgradeTypeVariants.BonusSpeed |
  ShipUpgradeTypeVariants.StrawHatBuff |
  ShipUpgradeTypeVariants.MarineBuff |
  ShipUpgradeTypeVariants.RevolutionaryBuff |
  ShipUpgradeTypeVariants.LogiaBuff |
  ShipUpgradeTypeVariants.ParameciaBuff |
  ShipUpgradeTypeVariants.ZoanBuff |
  ShipUpgradeTypeVariants.GamblerLuck |
  ShipUpgradeTypeVariants.FastLearner |
  ShipUpgradeTypeVariants.Plunderer |
  ShipUpgradeTypeVariants.Medic |
  ShipUpgradeTypeVariants.Arsenal;

let _cached_ShipUpgradeType_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const ShipUpgradeType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  BonusGold: { tag: "BonusGold" } as const,
  BonusHealth: { tag: "BonusHealth" } as const,
  BonusAttack: { tag: "BonusAttack" } as const,
  BonusDefense: { tag: "BonusDefense" } as const,
  BonusSpeed: { tag: "BonusSpeed" } as const,
  StrawHatBuff: { tag: "StrawHatBuff" } as const,
  MarineBuff: { tag: "MarineBuff" } as const,
  RevolutionaryBuff: { tag: "RevolutionaryBuff" } as const,
  LogiaBuff: { tag: "LogiaBuff" } as const,
  ParameciaBuff: { tag: "ParameciaBuff" } as const,
  ZoanBuff: { tag: "ZoanBuff" } as const,
  GamblerLuck: { tag: "GamblerLuck" } as const,
  FastLearner: { tag: "FastLearner" } as const,
  Plunderer: { tag: "Plunderer" } as const,
  Medic: { tag: "Medic" } as const,
  Arsenal: { tag: "Arsenal" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_ShipUpgradeType_type_value) return _cached_ShipUpgradeType_type_value;
    _cached_ShipUpgradeType_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_ShipUpgradeType_type_value.value.variants.push(
      { name: "BonusGold", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "BonusHealth", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "BonusAttack", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "BonusDefense", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "BonusSpeed", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "StrawHatBuff", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "MarineBuff", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "RevolutionaryBuff", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "LogiaBuff", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "ParameciaBuff", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "ZoanBuff", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "GamblerLuck", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "FastLearner", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Plunderer", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Medic", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Arsenal", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_ShipUpgradeType_type_value;
  },

  serialize(writer: __BinaryWriter, value: ShipUpgradeType): void {
      __AlgebraicTypeValue.serializeValue(writer, ShipUpgradeType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ShipUpgradeType {
      return __AlgebraicTypeValue.deserializeValue(reader, ShipUpgradeType.getTypeScriptAlgebraicType());
  },

}

export default ShipUpgradeType;


