// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { ItemComponent } from "./item_component_type";
// Mark import as potentially unused
declare type __keep_ItemComponent = ItemComponent;

import * as TreasureRewardTypeVariants from './treasure_reward_type_variants'

// The tagged union or sum type for the algebraic type `TreasureRewardType`.
export type TreasureRewardType = TreasureRewardTypeVariants.Gold |
  TreasureRewardTypeVariants.Item |
  TreasureRewardTypeVariants.Reroll |
  TreasureRewardTypeVariants.Experience;

let _cached_TreasureRewardType_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const TreasureRewardType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Gold: (value: number): TreasureRewardTypeVariants.Gold => ({ tag: "Gold", value }),
  Item: (value: ItemComponent): TreasureRewardTypeVariants.Item => ({ tag: "Item", value }),
  Reroll: { tag: "Reroll" } as const,
  Experience: { tag: "Experience" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_TreasureRewardType_type_value) return _cached_TreasureRewardType_type_value;
    _cached_TreasureRewardType_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_TreasureRewardType_type_value.value.variants.push(
      { name: "Gold", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "Item", algebraicType: ItemComponent.getTypeScriptAlgebraicType() },
      { name: "Reroll", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Experience", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_TreasureRewardType_type_value;
  },

  serialize(writer: __BinaryWriter, value: TreasureRewardType): void {
      __AlgebraicTypeValue.serializeValue(writer, TreasureRewardType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): TreasureRewardType {
      return __AlgebraicTypeValue.deserializeValue(reader, TreasureRewardType.getTypeScriptAlgebraicType());
  },

}

export default TreasureRewardType;


