// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

import { ItemComponent } from "./item_component_type";
// Mark import as potentially unused
declare type __keep_ItemComponent = ItemComponent;

export type AdminUpdateItemComponentStats = {
  component: ItemComponent,
  name: string | undefined,
  description: string | undefined,
  bonusAd: number | undefined,
  bonusCritChance: number | undefined,
  bonusAttackSpeed: number | undefined,
  bonusAp: number | undefined,
  bonusArmor: number | undefined,
  bonusMr: number | undefined,
  bonusMana: number | undefined,
  bonusHp: number | undefined,
};
/**
 * An object for generated helper functions.
 */
export const AdminUpdateItemComponentStats = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "component", algebraicType: ItemComponent.getTypeScriptAlgebraicType()},
        { name: "name", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "description", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "bonusAd", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32)},
        { name: "bonusCritChance", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.F32)},
        { name: "bonusAttackSpeed", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.F32)},
        { name: "bonusAp", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32)},
        { name: "bonusArmor", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32)},
        { name: "bonusMr", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32)},
        { name: "bonusMana", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32)},
        { name: "bonusHp", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32)},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AdminUpdateItemComponentStats): void {
    __AlgebraicTypeValue.serializeValue(writer, AdminUpdateItemComponentStats.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AdminUpdateItemComponentStats {
    return __AlgebraicTypeValue.deserializeValue(reader, AdminUpdateItemComponentStats.getTypeScriptAlgebraicType());
  },

}

export default AdminUpdateItemComponentStats;

