// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type Yoru = { tag: "Yoru" };
export type Kabuto = { tag: "Kabuto" };
export type Shusui = { tag: "Shusui" };
export type ClimaTact = { tag: "ClimaTact" };
export type ThunderTempo = { tag: "ThunderTempo" };
export type MirageFlower = { tag: "MirageFlower" };
export type AdamWood = { tag: "AdamWood" };
export type SeaKingScale = { tag: "SeaKingScale" };
export type ThousandSunnyHull = { tag: "ThousandSunnyHull" };
export type VivrCard = { tag: "VivrCard" };
export type LogPose = { tag: "LogPose" };
export type Poneglyph = { tag: "Poneglyph" };
export type GumGumFruit = { tag: "GumGumFruit" };
export type GomuGomuNoMi = { tag: "GomuGomuNoMi" };
export type HakiMastery = { tag: "HakiMastery" };

