// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { Crew } from "./crew_type";
import { ItemComponent } from "./item_component_type";
// Mark import as potentially unused
declare type __keep_ItemComponent = ItemComponent;
import { CompletedItem } from "./completed_item_type";
// Mark import as potentially unused
declare type __keep_CompletedItem = CompletedItem;
import { CrewRarity } from "./crew_rarity_type";
// Mark import as potentially unused
declare type __keep_CrewRarity = CrewRarity;
import { CrewTrait } from "./crew_trait_type";
// Mark import as potentially unused
declare type __keep_CrewTrait = CrewTrait;

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `crew`.
 *
 * Obtain a handle from the [`crew`] property on [`RemoteTables`],
 * like `ctx.db.crew`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.crew.on_insert(...)`.
 */
export class CrewTableHandle {
  tableCache: __TableCache<Crew>;

  constructor(tableCache: __TableCache<Crew>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Crew> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `crew`,
   * which allows point queries on the field of the same name
   * via the [`CrewIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.crew.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `crew`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): Crew | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Crew) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Crew) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Crew) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Crew) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Crew, newRow: Crew) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Crew, newRow: Crew) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
