// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { CrewRarity } from "./crew_rarity_type";
// Mark import as potentially unused
declare type __keep_CrewRarity = CrewRarity;
import { CrewTrait } from "./crew_trait_type";
// Mark import as potentially unused
declare type __keep_CrewTrait = CrewTrait;


export type CrewTemplate = {
  id: bigint,
  name: string,
  rarity: CrewRarity,
  trait1: CrewTrait,
  trait2: CrewTrait | undefined,
  maxHp: number,
  attack: number,
  defense: number,
  cost: number,
};
/**
 * An object for generated helper functions.
 */
export const CrewTemplate = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U64},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "rarity", algebraicType: CrewRarity.getTypeScriptAlgebraicType()},
        { name: "trait1", algebraicType: CrewTrait.getTypeScriptAlgebraicType()},
        { name: "trait2", algebraicType: __AlgebraicTypeValue.createOptionType(CrewTrait.getTypeScriptAlgebraicType())},
        { name: "maxHp", algebraicType: __AlgebraicTypeValue.U32},
        { name: "attack", algebraicType: __AlgebraicTypeValue.U32},
        { name: "defense", algebraicType: __AlgebraicTypeValue.U32},
        { name: "cost", algebraicType: __AlgebraicTypeValue.U32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: CrewTemplate): void {
    __AlgebraicTypeValue.serializeValue(writer, CrewTemplate.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): CrewTemplate {
    return __AlgebraicTypeValue.deserializeValue(reader, CrewTemplate.getTypeScriptAlgebraicType());
  },

}

export default CrewTemplate;


