// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.5.0 (commit 0712d3bfbd159367de09efeeeacb54c9d4f0ff61).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { AdminAddRecipe } from "./admin_add_recipe_reducer.ts";
export { AdminAddRecipe };
import { AdminDeleteRecipe } from "./admin_delete_recipe_reducer.ts";
export { AdminDeleteRecipe };
import { AdminUpdateCompletedItemStats } from "./admin_update_completed_item_stats_reducer.ts";
export { AdminUpdateCompletedItemStats };
import { AdminUpdateCrewTemplate } from "./admin_update_crew_template_reducer.ts";
export { AdminUpdateCrewTemplate };
import { AdminUpdateItemComponentStats } from "./admin_update_item_component_stats_reducer.ts";
export { AdminUpdateItemComponentStats };
import { AdminUpdateRecipe } from "./admin_update_recipe_reducer.ts";
export { AdminUpdateRecipe };
import { BuyCrew } from "./buy_crew_reducer.ts";
export { BuyCrew };
import { ClientConnected } from "./client_connected_reducer.ts";
export { ClientConnected };
import { ClientDisconnected } from "./client_disconnected_reducer.ts";
export { ClientDisconnected };
import { EquipItemToCrew } from "./equip_item_to_crew_reducer.ts";
export { EquipItemToCrew };
import { MoveCrew } from "./move_crew_reducer.ts";
export { MoveCrew };
import { RefreshShop } from "./refresh_shop_reducer.ts";
export { RefreshShop };
import { RegisterPlayer } from "./register_player_reducer.ts";
export { RegisterPlayer };
import { RemoveItemFromCrew } from "./remove_item_from_crew_reducer.ts";
export { RemoveItemFromCrew };
import { StartBattle } from "./start_battle_reducer.ts";
export { StartBattle };

// Import and reexport all table handle types
import { BattleTableHandle } from "./battle_table.ts";
export { BattleTableHandle };
import { CompletedItemStatsTableHandle } from "./completed_item_stats_table.ts";
export { CompletedItemStatsTableHandle };
import { CrewTableHandle } from "./crew_table.ts";
export { CrewTableHandle };
import { CrewTemplateTableHandle } from "./crew_template_table.ts";
export { CrewTemplateTableHandle };
import { ItemCombinationRecipeTableHandle } from "./item_combination_recipe_table.ts";
export { ItemCombinationRecipeTableHandle };
import { ItemComponentStatsTableHandle } from "./item_component_stats_table.ts";
export { ItemComponentStatsTableHandle };
import { PlayerTableHandle } from "./player_table.ts";
export { PlayerTableHandle };
import { PlayerItemTableHandle } from "./player_item_table.ts";
export { PlayerItemTableHandle };
import { ShopCrewTableHandle } from "./shop_crew_table.ts";
export { ShopCrewTableHandle };

// Import and reexport all types
import { Battle } from "./battle_type.ts";
export { Battle };
import { BattleStatus } from "./battle_status_type.ts";
export { BattleStatus };
import { CompletedItem } from "./completed_item_type.ts";
export { CompletedItem };
import { CompletedItemStats } from "./completed_item_stats_type.ts";
export { CompletedItemStats };
import { Crew } from "./crew_type.ts";
export { Crew };
import { CrewRarity } from "./crew_rarity_type.ts";
export { CrewRarity };
import { CrewTemplate } from "./crew_template_type.ts";
export { CrewTemplate };
import { CrewTrait } from "./crew_trait_type.ts";
export { CrewTrait };
import { ItemCombinationRecipe } from "./item_combination_recipe_type.ts";
export { ItemCombinationRecipe };
import { ItemComponent } from "./item_component_type.ts";
export { ItemComponent };
import { ItemComponentStats } from "./item_component_stats_type.ts";
export { ItemComponentStats };
import { Player } from "./player_type.ts";
export { Player };
import { PlayerItem } from "./player_item_type.ts";
export { PlayerItem };
import { ShipType } from "./ship_type_type.ts";
export { ShipType };
import { ShopCrew } from "./shop_crew_type.ts";
export { ShopCrew };

const REMOTE_MODULE = {
  tables: {
    battle: {
      tableName: "battle",
      rowType: Battle.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Battle.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    completed_item_stats: {
      tableName: "completed_item_stats",
      rowType: CompletedItemStats.getTypeScriptAlgebraicType(),
      primaryKey: "item",
      primaryKeyInfo: {
        colName: "item",
        colType: (CompletedItemStats.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    crew: {
      tableName: "crew",
      rowType: Crew.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Crew.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    crew_template: {
      tableName: "crew_template",
      rowType: CrewTemplate.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (CrewTemplate.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    item_combination_recipe: {
      tableName: "item_combination_recipe",
      rowType: ItemCombinationRecipe.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (ItemCombinationRecipe.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    item_component_stats: {
      tableName: "item_component_stats",
      rowType: ItemComponentStats.getTypeScriptAlgebraicType(),
      primaryKey: "component",
      primaryKeyInfo: {
        colName: "component",
        colType: (ItemComponentStats.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    player: {
      tableName: "player",
      rowType: Player.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: (Player.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    player_item: {
      tableName: "player_item",
      rowType: PlayerItem.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (PlayerItem.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    shop_crew: {
      tableName: "shop_crew",
      rowType: ShopCrew.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (ShopCrew.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    admin_add_recipe: {
      reducerName: "admin_add_recipe",
      argsType: AdminAddRecipe.getTypeScriptAlgebraicType(),
    },
    admin_delete_recipe: {
      reducerName: "admin_delete_recipe",
      argsType: AdminDeleteRecipe.getTypeScriptAlgebraicType(),
    },
    admin_update_completed_item_stats: {
      reducerName: "admin_update_completed_item_stats",
      argsType: AdminUpdateCompletedItemStats.getTypeScriptAlgebraicType(),
    },
    admin_update_crew_template: {
      reducerName: "admin_update_crew_template",
      argsType: AdminUpdateCrewTemplate.getTypeScriptAlgebraicType(),
    },
    admin_update_item_component_stats: {
      reducerName: "admin_update_item_component_stats",
      argsType: AdminUpdateItemComponentStats.getTypeScriptAlgebraicType(),
    },
    admin_update_recipe: {
      reducerName: "admin_update_recipe",
      argsType: AdminUpdateRecipe.getTypeScriptAlgebraicType(),
    },
    buy_crew: {
      reducerName: "buy_crew",
      argsType: BuyCrew.getTypeScriptAlgebraicType(),
    },
    client_connected: {
      reducerName: "client_connected",
      argsType: ClientConnected.getTypeScriptAlgebraicType(),
    },
    client_disconnected: {
      reducerName: "client_disconnected",
      argsType: ClientDisconnected.getTypeScriptAlgebraicType(),
    },
    equip_item_to_crew: {
      reducerName: "equip_item_to_crew",
      argsType: EquipItemToCrew.getTypeScriptAlgebraicType(),
    },
    move_crew: {
      reducerName: "move_crew",
      argsType: MoveCrew.getTypeScriptAlgebraicType(),
    },
    refresh_shop: {
      reducerName: "refresh_shop",
      argsType: RefreshShop.getTypeScriptAlgebraicType(),
    },
    register_player: {
      reducerName: "register_player",
      argsType: RegisterPlayer.getTypeScriptAlgebraicType(),
    },
    remove_item_from_crew: {
      reducerName: "remove_item_from_crew",
      argsType: RemoveItemFromCrew.getTypeScriptAlgebraicType(),
    },
    start_battle: {
      reducerName: "start_battle",
      argsType: StartBattle.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.5.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AdminAddRecipe", args: AdminAddRecipe }
| { name: "AdminDeleteRecipe", args: AdminDeleteRecipe }
| { name: "AdminUpdateCompletedItemStats", args: AdminUpdateCompletedItemStats }
| { name: "AdminUpdateCrewTemplate", args: AdminUpdateCrewTemplate }
| { name: "AdminUpdateItemComponentStats", args: AdminUpdateItemComponentStats }
| { name: "AdminUpdateRecipe", args: AdminUpdateRecipe }
| { name: "BuyCrew", args: BuyCrew }
| { name: "ClientConnected", args: ClientConnected }
| { name: "ClientDisconnected", args: ClientDisconnected }
| { name: "EquipItemToCrew", args: EquipItemToCrew }
| { name: "MoveCrew", args: MoveCrew }
| { name: "RefreshShop", args: RefreshShop }
| { name: "RegisterPlayer", args: RegisterPlayer }
| { name: "RemoveItemFromCrew", args: RemoveItemFromCrew }
| { name: "StartBattle", args: StartBattle }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  adminAddRecipe(component1: ItemComponent, component2: ItemComponent, result: CompletedItem) {
    const __args = { component1, component2, result };
    let __writer = new __BinaryWriter(1024);
    AdminAddRecipe.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("admin_add_recipe", __argsBuffer, this.setCallReducerFlags.adminAddRecipeFlags);
  }

  onAdminAddRecipe(callback: (ctx: ReducerEventContext, component1: ItemComponent, component2: ItemComponent, result: CompletedItem) => void) {
    this.connection.onReducer("admin_add_recipe", callback);
  }

  removeOnAdminAddRecipe(callback: (ctx: ReducerEventContext, component1: ItemComponent, component2: ItemComponent, result: CompletedItem) => void) {
    this.connection.offReducer("admin_add_recipe", callback);
  }

  adminDeleteRecipe(recipeId: bigint) {
    const __args = { recipeId };
    let __writer = new __BinaryWriter(1024);
    AdminDeleteRecipe.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("admin_delete_recipe", __argsBuffer, this.setCallReducerFlags.adminDeleteRecipeFlags);
  }

  onAdminDeleteRecipe(callback: (ctx: ReducerEventContext, recipeId: bigint) => void) {
    this.connection.onReducer("admin_delete_recipe", callback);
  }

  removeOnAdminDeleteRecipe(callback: (ctx: ReducerEventContext, recipeId: bigint) => void) {
    this.connection.offReducer("admin_delete_recipe", callback);
  }

  adminUpdateCompletedItemStats(item: CompletedItem, name: string | undefined, description: string | undefined, bonusAd: number | undefined, bonusCritChance: number | undefined, bonusCritDamage: number | undefined, bonusAttackSpeed: number | undefined, bonusAp: number | undefined, bonusArmor: number | undefined, bonusMr: number | undefined, bonusMana: number | undefined, bonusHp: number | undefined, bonusHpRegen: number | undefined, hasSplash: boolean | undefined, armorShred: number | undefined) {
    const __args = { item, name, description, bonusAd, bonusCritChance, bonusCritDamage, bonusAttackSpeed, bonusAp, bonusArmor, bonusMr, bonusMana, bonusHp, bonusHpRegen, hasSplash, armorShred };
    let __writer = new __BinaryWriter(1024);
    AdminUpdateCompletedItemStats.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("admin_update_completed_item_stats", __argsBuffer, this.setCallReducerFlags.adminUpdateCompletedItemStatsFlags);
  }

  onAdminUpdateCompletedItemStats(callback: (ctx: ReducerEventContext, item: CompletedItem, name: string | undefined, description: string | undefined, bonusAd: number | undefined, bonusCritChance: number | undefined, bonusCritDamage: number | undefined, bonusAttackSpeed: number | undefined, bonusAp: number | undefined, bonusArmor: number | undefined, bonusMr: number | undefined, bonusMana: number | undefined, bonusHp: number | undefined, bonusHpRegen: number | undefined, hasSplash: boolean | undefined, armorShred: number | undefined) => void) {
    this.connection.onReducer("admin_update_completed_item_stats", callback);
  }

  removeOnAdminUpdateCompletedItemStats(callback: (ctx: ReducerEventContext, item: CompletedItem, name: string | undefined, description: string | undefined, bonusAd: number | undefined, bonusCritChance: number | undefined, bonusCritDamage: number | undefined, bonusAttackSpeed: number | undefined, bonusAp: number | undefined, bonusArmor: number | undefined, bonusMr: number | undefined, bonusMana: number | undefined, bonusHp: number | undefined, bonusHpRegen: number | undefined, hasSplash: boolean | undefined, armorShred: number | undefined) => void) {
    this.connection.offReducer("admin_update_completed_item_stats", callback);
  }

  adminUpdateCrewTemplate(templateId: bigint, name: string | undefined, maxHp: number | undefined, attack: number | undefined, defense: number | undefined, cost: number | undefined) {
    const __args = { templateId, name, maxHp, attack, defense, cost };
    let __writer = new __BinaryWriter(1024);
    AdminUpdateCrewTemplate.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("admin_update_crew_template", __argsBuffer, this.setCallReducerFlags.adminUpdateCrewTemplateFlags);
  }

  onAdminUpdateCrewTemplate(callback: (ctx: ReducerEventContext, templateId: bigint, name: string | undefined, maxHp: number | undefined, attack: number | undefined, defense: number | undefined, cost: number | undefined) => void) {
    this.connection.onReducer("admin_update_crew_template", callback);
  }

  removeOnAdminUpdateCrewTemplate(callback: (ctx: ReducerEventContext, templateId: bigint, name: string | undefined, maxHp: number | undefined, attack: number | undefined, defense: number | undefined, cost: number | undefined) => void) {
    this.connection.offReducer("admin_update_crew_template", callback);
  }

  adminUpdateItemComponentStats(component: ItemComponent, name: string | undefined, description: string | undefined, bonusAd: number | undefined, bonusCritChance: number | undefined, bonusAttackSpeed: number | undefined, bonusAp: number | undefined, bonusArmor: number | undefined, bonusMr: number | undefined, bonusMana: number | undefined, bonusHp: number | undefined) {
    const __args = { component, name, description, bonusAd, bonusCritChance, bonusAttackSpeed, bonusAp, bonusArmor, bonusMr, bonusMana, bonusHp };
    let __writer = new __BinaryWriter(1024);
    AdminUpdateItemComponentStats.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("admin_update_item_component_stats", __argsBuffer, this.setCallReducerFlags.adminUpdateItemComponentStatsFlags);
  }

  onAdminUpdateItemComponentStats(callback: (ctx: ReducerEventContext, component: ItemComponent, name: string | undefined, description: string | undefined, bonusAd: number | undefined, bonusCritChance: number | undefined, bonusAttackSpeed: number | undefined, bonusAp: number | undefined, bonusArmor: number | undefined, bonusMr: number | undefined, bonusMana: number | undefined, bonusHp: number | undefined) => void) {
    this.connection.onReducer("admin_update_item_component_stats", callback);
  }

  removeOnAdminUpdateItemComponentStats(callback: (ctx: ReducerEventContext, component: ItemComponent, name: string | undefined, description: string | undefined, bonusAd: number | undefined, bonusCritChance: number | undefined, bonusAttackSpeed: number | undefined, bonusAp: number | undefined, bonusArmor: number | undefined, bonusMr: number | undefined, bonusMana: number | undefined, bonusHp: number | undefined) => void) {
    this.connection.offReducer("admin_update_item_component_stats", callback);
  }

  adminUpdateRecipe(recipeId: bigint, component1: ItemComponent | undefined, component2: ItemComponent | undefined, result: CompletedItem | undefined) {
    const __args = { recipeId, component1, component2, result };
    let __writer = new __BinaryWriter(1024);
    AdminUpdateRecipe.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("admin_update_recipe", __argsBuffer, this.setCallReducerFlags.adminUpdateRecipeFlags);
  }

  onAdminUpdateRecipe(callback: (ctx: ReducerEventContext, recipeId: bigint, component1: ItemComponent | undefined, component2: ItemComponent | undefined, result: CompletedItem | undefined) => void) {
    this.connection.onReducer("admin_update_recipe", callback);
  }

  removeOnAdminUpdateRecipe(callback: (ctx: ReducerEventContext, recipeId: bigint, component1: ItemComponent | undefined, component2: ItemComponent | undefined, result: CompletedItem | undefined) => void) {
    this.connection.offReducer("admin_update_recipe", callback);
  }

  buyCrew(shopCrewId: bigint, slotIndex: number | undefined) {
    const __args = { shopCrewId, slotIndex };
    let __writer = new __BinaryWriter(1024);
    BuyCrew.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("buy_crew", __argsBuffer, this.setCallReducerFlags.buyCrewFlags);
  }

  onBuyCrew(callback: (ctx: ReducerEventContext, shopCrewId: bigint, slotIndex: number | undefined) => void) {
    this.connection.onReducer("buy_crew", callback);
  }

  removeOnBuyCrew(callback: (ctx: ReducerEventContext, shopCrewId: bigint, slotIndex: number | undefined) => void) {
    this.connection.offReducer("buy_crew", callback);
  }

  onClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_connected", callback);
  }

  removeOnClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_connected", callback);
  }

  onClientDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_disconnected", callback);
  }

  removeOnClientDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_disconnected", callback);
  }

  equipItemToCrew(crewId: bigint, component: ItemComponent) {
    const __args = { crewId, component };
    let __writer = new __BinaryWriter(1024);
    EquipItemToCrew.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("equip_item_to_crew", __argsBuffer, this.setCallReducerFlags.equipItemToCrewFlags);
  }

  onEquipItemToCrew(callback: (ctx: ReducerEventContext, crewId: bigint, component: ItemComponent) => void) {
    this.connection.onReducer("equip_item_to_crew", callback);
  }

  removeOnEquipItemToCrew(callback: (ctx: ReducerEventContext, crewId: bigint, component: ItemComponent) => void) {
    this.connection.offReducer("equip_item_to_crew", callback);
  }

  moveCrew(crewId: bigint, newSlot: number | undefined) {
    const __args = { crewId, newSlot };
    let __writer = new __BinaryWriter(1024);
    MoveCrew.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("move_crew", __argsBuffer, this.setCallReducerFlags.moveCrewFlags);
  }

  onMoveCrew(callback: (ctx: ReducerEventContext, crewId: bigint, newSlot: number | undefined) => void) {
    this.connection.onReducer("move_crew", callback);
  }

  removeOnMoveCrew(callback: (ctx: ReducerEventContext, crewId: bigint, newSlot: number | undefined) => void) {
    this.connection.offReducer("move_crew", callback);
  }

  refreshShop() {
    this.connection.callReducer("refresh_shop", new Uint8Array(0), this.setCallReducerFlags.refreshShopFlags);
  }

  onRefreshShop(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("refresh_shop", callback);
  }

  removeOnRefreshShop(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("refresh_shop", callback);
  }

  registerPlayer(name: string) {
    const __args = { name };
    let __writer = new __BinaryWriter(1024);
    RegisterPlayer.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("register_player", __argsBuffer, this.setCallReducerFlags.registerPlayerFlags);
  }

  onRegisterPlayer(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.onReducer("register_player", callback);
  }

  removeOnRegisterPlayer(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.offReducer("register_player", callback);
  }

  removeItemFromCrew(crewId: bigint, slot: number) {
    const __args = { crewId, slot };
    let __writer = new __BinaryWriter(1024);
    RemoveItemFromCrew.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("remove_item_from_crew", __argsBuffer, this.setCallReducerFlags.removeItemFromCrewFlags);
  }

  onRemoveItemFromCrew(callback: (ctx: ReducerEventContext, crewId: bigint, slot: number) => void) {
    this.connection.onReducer("remove_item_from_crew", callback);
  }

  removeOnRemoveItemFromCrew(callback: (ctx: ReducerEventContext, crewId: bigint, slot: number) => void) {
    this.connection.offReducer("remove_item_from_crew", callback);
  }

  startBattle() {
    this.connection.callReducer("start_battle", new Uint8Array(0), this.setCallReducerFlags.startBattleFlags);
  }

  onStartBattle(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("start_battle", callback);
  }

  removeOnStartBattle(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("start_battle", callback);
  }

}

export class SetReducerFlags {
  adminAddRecipeFlags: __CallReducerFlags = 'FullUpdate';
  adminAddRecipe(flags: __CallReducerFlags) {
    this.adminAddRecipeFlags = flags;
  }

  adminDeleteRecipeFlags: __CallReducerFlags = 'FullUpdate';
  adminDeleteRecipe(flags: __CallReducerFlags) {
    this.adminDeleteRecipeFlags = flags;
  }

  adminUpdateCompletedItemStatsFlags: __CallReducerFlags = 'FullUpdate';
  adminUpdateCompletedItemStats(flags: __CallReducerFlags) {
    this.adminUpdateCompletedItemStatsFlags = flags;
  }

  adminUpdateCrewTemplateFlags: __CallReducerFlags = 'FullUpdate';
  adminUpdateCrewTemplate(flags: __CallReducerFlags) {
    this.adminUpdateCrewTemplateFlags = flags;
  }

  adminUpdateItemComponentStatsFlags: __CallReducerFlags = 'FullUpdate';
  adminUpdateItemComponentStats(flags: __CallReducerFlags) {
    this.adminUpdateItemComponentStatsFlags = flags;
  }

  adminUpdateRecipeFlags: __CallReducerFlags = 'FullUpdate';
  adminUpdateRecipe(flags: __CallReducerFlags) {
    this.adminUpdateRecipeFlags = flags;
  }

  buyCrewFlags: __CallReducerFlags = 'FullUpdate';
  buyCrew(flags: __CallReducerFlags) {
    this.buyCrewFlags = flags;
  }

  equipItemToCrewFlags: __CallReducerFlags = 'FullUpdate';
  equipItemToCrew(flags: __CallReducerFlags) {
    this.equipItemToCrewFlags = flags;
  }

  moveCrewFlags: __CallReducerFlags = 'FullUpdate';
  moveCrew(flags: __CallReducerFlags) {
    this.moveCrewFlags = flags;
  }

  refreshShopFlags: __CallReducerFlags = 'FullUpdate';
  refreshShop(flags: __CallReducerFlags) {
    this.refreshShopFlags = flags;
  }

  registerPlayerFlags: __CallReducerFlags = 'FullUpdate';
  registerPlayer(flags: __CallReducerFlags) {
    this.registerPlayerFlags = flags;
  }

  removeItemFromCrewFlags: __CallReducerFlags = 'FullUpdate';
  removeItemFromCrew(flags: __CallReducerFlags) {
    this.removeItemFromCrewFlags = flags;
  }

  startBattleFlags: __CallReducerFlags = 'FullUpdate';
  startBattle(flags: __CallReducerFlags) {
    this.startBattleFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get battle(): BattleTableHandle {
    // clientCache is a private property
    return new BattleTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Battle>(REMOTE_MODULE.tables.battle));
  }

  get completedItemStats(): CompletedItemStatsTableHandle {
    // clientCache is a private property
    return new CompletedItemStatsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<CompletedItemStats>(REMOTE_MODULE.tables.completed_item_stats));
  }

  get crew(): CrewTableHandle {
    // clientCache is a private property
    return new CrewTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Crew>(REMOTE_MODULE.tables.crew));
  }

  get crewTemplate(): CrewTemplateTableHandle {
    // clientCache is a private property
    return new CrewTemplateTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<CrewTemplate>(REMOTE_MODULE.tables.crew_template));
  }

  get itemCombinationRecipe(): ItemCombinationRecipeTableHandle {
    // clientCache is a private property
    return new ItemCombinationRecipeTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ItemCombinationRecipe>(REMOTE_MODULE.tables.item_combination_recipe));
  }

  get itemComponentStats(): ItemComponentStatsTableHandle {
    // clientCache is a private property
    return new ItemComponentStatsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ItemComponentStats>(REMOTE_MODULE.tables.item_component_stats));
  }

  get player(): PlayerTableHandle {
    // clientCache is a private property
    return new PlayerTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Player>(REMOTE_MODULE.tables.player));
  }

  get playerItem(): PlayerItemTableHandle {
    // clientCache is a private property
    return new PlayerItemTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PlayerItem>(REMOTE_MODULE.tables.player_item));
  }

  get shopCrew(): ShopCrewTableHandle {
    // clientCache is a private property
    return new ShopCrewTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ShopCrew>(REMOTE_MODULE.tables.shop_crew));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
