// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as ItemComponentVariants from './item_component_variants'

// The tagged union or sum type for the algebraic type `ItemComponent`.
export type ItemComponent = ItemComponentVariants.Cutlass |
  ItemComponentVariants.SniperGoggles |
  ItemComponentVariants.ShellDial |
  ItemComponentVariants.ToneDial |
  ItemComponentVariants.SeastoneFragment |
  ItemComponentVariants.TidalCloak |
  ItemComponentVariants.EnergyDrink |
  ItemComponentVariants.Meat;

// A value with helper functions to construct the type.
export const ItemComponent = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Cutlass: { tag: "Cutlass" } as const,
  SniperGoggles: { tag: "SniperGoggles" } as const,
  ShellDial: { tag: "ShellDial" } as const,
  ToneDial: { tag: "ToneDial" } as const,
  SeastoneFragment: { tag: "SeastoneFragment" } as const,
  TidalCloak: { tag: "TidalCloak" } as const,
  EnergyDrink: { tag: "EnergyDrink" } as const,
  Meat: { tag: "Meat" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Cutlass", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "SniperGoggles", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ShellDial", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ToneDial", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "SeastoneFragment", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "TidalCloak", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "EnergyDrink", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Meat", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ItemComponent): void {
      __AlgebraicTypeValue.serializeValue(writer, ItemComponent.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ItemComponent {
      return __AlgebraicTypeValue.deserializeValue(reader, ItemComponent.getTypeScriptAlgebraicType());
  },

}

export default ItemComponent;


